name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-all-services:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Remove nested .git folders (if any)
      run: |
        find . -name ".git" -type d -not -path "./.git" -exec rm -rf {} +

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Run tests in all services
      run: |
        for dir in auth-service product-service cart-service order-service payment-service inventory-service notification-service; do
          if [ -f "$dir/package.json" ]; then
            echo "Testing $dir..."
            cd $dir
            npm install
            if npm run | grep -q "test"; then
              npm test || continue-on-error: true
            else
              echo "No test script for $dir. Skipping."
            fi
            cd ..
          else
            echo "No package.json in $dir. Skipping."
          fi
        done
