name: Microservices CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-services:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Run tests for all microservices
      run: |
        SERVICES=("auth-service" "product-service" "cart-service" "order-service" "payment-service" "inventory-service" "notification-service")

        for service in "${SERVICES[@]}"; do
          echo "🔍 Checking $service..."

          if [ -f "$service/package.json" ]; then
            cd $service

            echo "📦 Installing dependencies in $service..."
            npm install

            HAS_TEST=$(npm run | grep -i test)

            if [[ "$HAS_TEST" == *"test"* ]]; then
              echo "🧪 Running tests in $service..."
              # Try the test; if it fails, just log and move on
              npm test || echo "⚠️ $service tests failed (but continuing)..."
            else
              echo "⏭️  No test script in $service. Skipping."
            fi

            cd ..
          else
            echo "🚫 No package.json found in $service. Skipping."
          fi

          echo "--------------------------------------"
        done
